version: '3.8'

services:
#   nginx:
#     container_name: nginx
#     build: 
#       context: ./requirements/nginx
#       dockerfile: Dockerfile
#     ports:
#       - "443:443"
#     volumes:
#       - requirements/volumes/wordpress:/var/www/html
#     restart: always
  
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes: 
    - ./requirements/volumes/db:/var/lib/mysql
    restart: always


# volumes:
#   db: 
#   wordpress:
    