version: '3.8'

services:
  # frontend:
  #   build: 
  #   ports:
  #     -
  # DB:
  #   build: 
  #   ports:
  #     -
  NGINX:
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./srcs/requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./srcs/requirements/nginx/tools/ssl:/nginx/ssl
    