version: '3.8'

services:
#   nginx:
#     container_name: nginx
#     build: 
#       context: ./requirements/nginx
#       dockerfile: Dockerfile
#     ports:
#       - "443:443"
#     volumes:
#       -  ./requirements/volumes_tmp/wordpress:/var/www/html
#     restart: always
  mariadb:
    env_file:
      - .env
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
     -  ./requirements/volumes_tmp/db:/var/lib/mysql
    restart: on-failure


# volumes:
#   db:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./requirements/volumes_tmp/db
#   wordpress:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./requirements/volumes_tmp/wordpress