# version: '3.8'

# services:
#   nginx:
#     build: 
#       context: .
#     ports:
#       - "443:443"
#     volumes:
#       -  ../volumes_tmp/nginx:/var/www/
#     #   - ./conf/nginx.conf:/etc/nginx/nginx.conf
#     restart: always
    